import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-br from-[#bfe9ff] to-[#ffcdf3]">
          <div className="relative flex min-h-screen">
            <Sidebar />
            <header className="pointer-events-none absolute right-8 top-6 text-sm font-semibold tracking-wide text-zinc-800">
              Judy&apos;s Humor Project
            </header>
            <main className="flex-1 px-6 py-10">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
